
name: "askguess"
type: "question_answer"

settings:
  label_path: "environments/askguess/test_labels.json"
  mode: "hard"
  max_rounds: 10
  n: 1

evaluation:
  metrics:
    - "success_rate"
    - "average_rounds"
    - "question_quality"
  
askguess_specific:
  difficulty_levels: ["easy", "medium", "hard"]
  categories: ["animals", "objects", "concepts"] 