name: "diplomacy"
type: "strategy"

settings:
  max_rounds: 3  
  debug: true
  diplomacy_model_name: ${model.name}

roles:
  diplomacy_model_name: ${model.name}

evaluation:
  metrics:
    - "rounds_played"
    - "supply_centers"
    - "winner"
    - "strategic_decisions"
    - "negotiation_effectiveness" 