name: "spyfall"
type: "social_deduction"

settings:
  label_path: "environments/spyfall/prompts/labels.txt"
  n: 10
  embedding_model: "auto"
  embedding_model_name: "text-embedding-3-large"
  perplexity_model: "auto"

roles:
  spy_model_name: ${model.name}
  villager_model_name: ${model.name}

evaluation:
  metrics:
    - "spy_win_rate"
    - "villager_win_rate"
    - "detection_accuracy"
    - "blending_quality" 