name: "openai"
provider: "openai"

settings:
  temperature: 0.7
  max_tokens: 4096
  top_p: 1.0

available_models:
  - "gpt-4o"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"

default_model: "gpt-4o"

api:
  key: ${oc.env:OPENAI_API_KEY}
  organization: ${oc.env:OPENAI_ORG_ID,null}
  timeout: 60 