# @package model

name: "openai"
provider: "openai"

# Настройки модели
settings:
  temperature: 0.7
  max_tokens: 4096
  top_p: 1.0

# Доступные модели
available_models:
  - "gpt-4o"
  - "gpt-4-turbo"
  - "gpt-3.5-turbo"

# Модель по умолчанию
default_model: "gpt-4o"

# API настройки
api:
  key: ${oc.env:OPENAI_API_KEY}
  organization: ${oc.env:OPENAI_ORG_ID,null}
  timeout: 60 